# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbtest',
                'doc_host': 'https://ronaldlens.github.io',
                'git_url': 'https://github.com/ronaldlens/nbtest',
                'lib_path': 'nbtest'},
  'syms': {'nbtest.core': {'nbtest.core.foo': ('core.html#foo', 'nbtest/core.py')}}}
